@startuml
left to right direction
actor Utilisateur as U
actor Marie as M

rectangle "Site Web" {
  U --> (Accueil)
  U --> (Informations)
  U --> (Réservation Entretien)
  U --> (Réservation Hebdomadaire)
  U -Consulte-> (Blog)
  U --> (Blog +)
  (Réservation Entretien) --> M
  (Réservation Hebdomadaire) --> M
}
@enduml