@startuml
left to right direction
rectangle "Navigation du site" {
  (Accueil) <--> (Réservation Entretien)
  (Accueil) <--> (Blog)
  (Réservation Entretien) --> (Réservation Hebdomadaire)  :Ajouter un entretien
  (Réservation Hebdomadaire) --> (Blog +)  : semaine terminée
}
@enduml