@startgantt 
[Maquettage] requires 5 days
[Formation] requires 12 days
[Conception proto] requires 6 days
[Devellopement Accueil Reservation] requires 12 days
[Dev Blog] requires 12 days
[Dev Admin] requires 12 days
[Test] requires 5 days
[Finalisation] requires 12 days


Project starts 2024-04-08
[Formation] starts 2024-04-08
[Conception proto] starts 2024-04-15
[Maquettage] starts 2024-04-08
[Devellopement Accueil Reservation] starts 2024-04-22
[Dev Blog] starts 2024-05-06
[Dev Admin] starts 2024-05-06
[Test] starts 2024-05-20
[Finalisation] starts 2024-05-20
@endgantt