@startuml
start
:Utilisateur remplit formulaire réservation;
while (Marie disponible ?) is (Non)
  :Vérifier disponibilités;
  if (Marie disponible ?) then (Oui)
    :Confirmer réservation;
  else (Non)
    :Proposer autres créneaux;
  endif
endwhile (Oui)
stop
@enduml