@startuml
left to right direction
actor Utilisateur as U
actor Marie as M

rectangle "Site Web" {
  U --> (Accueil)
  U --> (Réservation Entretien)
  U --> (Réservation Hebdomadaire) : si il a passé l'entretient
  U --> (Blog) : "Consulte"
  U --> (Blog +) : si il a passé 1 semaine réservée
  (Réservation Entretien) --> M 
  (Réservation Hebdomadaire) --> M 
  M --> (Blog) : Modifie/Ajoute
  M -left-> (Blog +) : Modifie/Ajoute
}
@enduml